apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attic
  namespace: attic
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - attic.groovyreserve.com
    - attic.cs.groovyreserve.com
  rules:
  - host: attic.groovyreserve.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: attic
            port:
              number: 80
  - host: attic.cs.groovyreserve.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: attic
            port:
              number: 80