[helium]
src.github_tag = "imputnet/helium-linux"
fetch.url = "https://github.com/imputnet/helium-linux/releases/download/$ver/helium-$ver-x86_64.AppImage"

[ghostty-dmg]
src.manual = "1.2.3"
fetch.url = "https://release.files.ghostty.org/$ver/Ghostty.dmg"
