excludes = ["*.lock", ".gitignore"]
on-unmatched = "warn"

[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.biome]
command = "biome"
includes = ["*.json", "*.jsonc"]
excludes = ["modules/user/hjem/configs/zed/keymap.json"] # False positive
options = [
  "format",
  "--no-errors-on-unmatched",
  "--use-editorconfig=true",
  "--write",
]

[formatter.mdformat]
command = "mdformat"
includes = ["*.md"]

[formatter.taplo]
command = "taplo"
includes = ["*.toml"]
options = ["format"]
