[type.nix]
# Catch the UUIDs for my drives currently
extend-glob = ["*filesystems.nix"]
extend-words = { "BA" = "BA" }

[type.png]
extend-glob = ["*.png"]
check-file = false

[type.gz]
extend-glob = ["*.gz"]
check-file = false

[default.extend-words]
# Random key from dnscrypt-proxy
RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3 = "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3"

[default]
extend-ignore-identifiers-re = ['LESS_TERMCAP_\w+$']
