[type.nix]
# Catch the UUIDs for my drives currently
extend-glob = ["*filesystems.nix"]
extend-words = { "BA" = "BA" }

[type.png]
extend-glob = ["*.png"]
check-file = false

[type.gz]
extend-glob = ["*.gz"]
check-file = false

[default]
extend-ignore-re = [
  # Ignore lines ending with `# typos:ignore-line`
  "(?Rm)^.*#\\s*typos:ignore-line$",
]
extend-ignore-identifiers-re = ['LESS_TERMCAP_\w+$']
