apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-groovyreserve-com
  namespace: kube-system
spec:
  secretName: wildcard-groovyreserve-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.groovyreserve.com"
  dnsNames:
  - "*.cs.groovyreserve.com"
  - "*.groovyreserve.com"
